# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-27 16:37
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_title', models.CharField(max_length=100, null=True, verbose_name='品种')),
                ('g_pic', models.ImageField(default='images/blog/default.jpg', upload_to='images/blog/%Y/%m/', verbose_name='商品图片')),
                ('g_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格')),
                ('g_unit', models.CharField(max_length=50, null=True, verbose_name='单位')),
                ('g_click', models.IntegerField(default='0', null=True, verbose_name='点击数')),
                ('g_desc', models.CharField(max_length=50, verbose_name='商品描述')),
                ('g_stock', models.IntegerField(null=True, verbose_name='数量')),
                ('content', DjangoUeditor.models.UEditorField(null=True, verbose_name='介绍')),
            ],
            options={
                'verbose_name_plural': '商品',
                'db_table': 'df_goods_goodinfo',
                'verbose_name': '商品',
            },
        ),
        migrations.CreateModel(
            name='Commodity_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='商品分类')),
                ('class_name', models.CharField(max_length=50, null=True, verbose_name='商品种类')),
                ('type_img', models.ImageField(default='', upload_to='images/type/%Y/%m/', verbose_name='商品种类图片')),
            ],
            options={
                'verbose_name_plural': '商品种类',
                'db_table': 'df_goods_typeinfo',
                'verbose_name': '商品种类',
            },
        ),
        migrations.CreateModel(
            name='Detailinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': '订单详情',
                'db_table': 'df_order_orderdetailinfo',
                'verbose_name': '订单详情',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('o_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='订单编号')),
                ('o_date', models.DateTimeField(auto_now_add=True, verbose_name='订单日期')),
                ('o_pay', models.BooleanField(choices=[(True, '已支付'), (False, '未支付')], default=False, verbose_name='是否支付')),
                ('o_total_price', models.CharField(max_length=100, verbose_name='总价')),
            ],
            options={
                'verbose_name_plural': '订单',
                'db_table': 'df_order_orderinfo',
                'verbose_name': '订单',
            },
        ),
        migrations.CreateModel(
            name='ShoopCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(null=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Commodity')),
            ],
            options={
                'verbose_name_plural': '购物车',
                'db_table': 'df_cart_cartinfo',
                'verbose_name': '购物车',
            },
        ),
    ]
