# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-27 16:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoopcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Commodity', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Order', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='g_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Commodity_type', verbose_name='商品类型'),
        ),
    ]
